config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :jobs do
    resources :my_jobs, only: [:create ]
  end

  resources :my_jobs, only: [:index]

  resources :reviews, only: [:index, :new, :create]

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :users do
    resources :reviews, only: [ :new, :create ]
  end

  post "my_jobs/change_status", to: "my_jobs#change_status"

  post '/change_locale', to: 'application#change_locale'

  resources :meetings
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :my_jobs

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :description, :category, :address, :city, :qty_hour, presence: true
  validates :price_per_hour, :end_date, :start_time, :end_time, presence: true

  has_one_attached :photo


  validate :start_date_after_today
  validate :end_date_after_start_date

  include PgSearch::Model
    pg_search_scope :search_by_name_and_description_and_city,
    against: [ :name, :description, :city, :category, :price_per_hour, :start_date ],
    using: {
      tsearch: { prefix: true }
    }

#  enum :category, {
#     painting: 1,
#     babysitting: 2,
#     deliveries: 3,
#     cleaning: 4,
#     petsitting: 5,
#     others: 6
#     }

    private

    def start_date_after_today
      if start_date.nil?
        errors.add(:start_date, 'cannot be blank')
      elsif start_date <= Date.today
        errors.add(:start_date, 'must be after the current date')
      end

    end

    def end_date_after_start_date
      if start_date.nil?
        errors.add(:start_date, 'cannot be blank')
      elsif end_date < start_date
      errors.add(:end_date, 'Must be after the star date')
      end
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index



    jobs_with_accepted_pending = MyJob.select(:job_id).distinct.where(status: "accepted").pluck(:job_id)
    # @jobs = Job.all
    @jobs =Job.where.not(id: jobs_with_accepted_pending)


    @jobs = @jobs.search_by_name_and_description_and_city(params[:category]) if params[:category].present?

      @jobs = @jobs.search_by_name_and_description_and_city(params[:query]) if params[:query].present?


      @jobs = @jobs.search_by_name_and_description_and_city(params[:city]) if params[:city].present?

      @jobs = @jobs.search_by_name_and_description_and_city(params[:price]) if params[:price].present?

      @jobs = @jobs.search_by_name_and_description_and_city(params[:date]) if params[:date].present?




    # @tournaments = policy_scope(Tournament.all)
    # @tournaments = policy_scope(@tournaments.where(category: params[:category])) if params[:category].present?
    # @tournaments = policy_scope(@tournaments.where(type: params[:type])) if params[:type].present?
    # @tournaments = policy_scope(@tournaments.where(type: params[:type])) if params[:type].present?
    # @tournaments = policy_scope(@tournaments.where(“price <= (?)“, params[:max_price])) if params[:max_price].present?
    # @tournaments = policy_scope(@tournaments.where(“start_date >= (?)“, params[:start_date])) if params[:start_date].present?
    # @tournaments = policy_scope(@tournaments.where(“end_date <= (?)“, params[:end_date])) if params[:end_date].present?
      # @markers = @jobs.geocoded.map do |job|
      #   {
      #     lat: job.latitude,
      #     lng: job.longitude,
      #     info_window_html: render_to_string(partial: "info_window", locals: { job: job }, formats: [:html])
      #   }
      # end

      respond_to do |format|
        format.html
        format.text { render partial: "jobs/list", locals: { jobs: @jobs }, formats: [:html] }
      end
    end

    def show
      @job = Job.find(params[:id])
      @my_jobs = Job.where(user: current_user)
      flash[:message] = t("thanksforapplying")
      @markers =
        [{
          lat: @job.latitude,
          lng: @job.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: { job: @job }, formats: [:html])
        }]
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params)
      @job.user_id = current_user.id
      if @job.save
        redirect_to my_jobs_path, notice: t("jobsaved")
      else

        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @job = Job.find(params[:id])
    end

    def update
      @job = Job.find(params[:id])
      @job.update(job_params)
      redirect_to my_jobs_path, notice: t("jobupdated")
    end

  def destroy
    @job = Job.find(params[:id])
    MyJob.where(job_id: @job.id).destroy_all

    @job.destroy
    redirect_to my_jobs_path, status: :see_other
  end

  private
  def job_params
    params.require(:job).permit(:name, :address, :description, :category, :qty_hour, :city, :price_per_hour, :start_date, :end_date, :start_time, :end_time, :photo)
  end
end

app/views/jobs/_category.html.erb
<%= category.category %>

app/views/jobs/_info_window.html.erb
<h4><%= job.name %></h4>
<p><%= job.address %></p>

app/views/jobs/_list.html.erb
<div data-search-jobs-target="list">
  <%# <p class="h3"> %>

  <div>
    <p class="h3">
      <% if params[:query].blank? %>
        <h5><%= pluralize jobs.count, t("AvailableJobs")%></h5>
      <% else %>
        <%= pluralize jobs.count, "result" %> for <code><%= params[:query] %></code>
      <% end %>
    </p>
  </div>

    <div class="jobs mt-4 mb-4">
      <div class="row mt-4">
        <% @jobs.each do |job| %>
        <div class="col-lg-4 col-md-4 col d-flex justify-content-center">
          <div class="card-venues m-4 justify-content-center">
            <div class = "card-jobs">
              <% if job.photo.key != nil %>
                  <%= cl_image_tag job.photo.key, height: 300, width: 300, crop: :fill %>
                <% else %>
              <% end %>
                <div class="card-jobs-info mt-2 mb-2">
                  <h4><%= job.name.titleize %></h4>
                  <p><%= job.description.capitalize.truncate(100) %></p>
                  <p><%= job.city.titleize %></p>
                  <div class = "button_card">
                  <%= link_to t("moredetails"), job_path(job), class: "btn btn-success" %>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/jobs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2> <%= t("updateyourjob") %> </h2>
      <div class = "card-edit">
        <%= simple_form_for @job  do |f| %>
          <%= f.input :name, label: t("name")  %>
          <%= f.input :address, label: t("address")  %>
          <%= f.input :city, label: t("city")  %>
          <%= f.input :category, collection: [t('painting'), t('babysitting'), t('deliveries'), t('cleaning'), t('petsitting'), t('others')], include_blank: false, label: t('category')  %>
          <%= f.input :qty_hour, label: t("qtyhour")  %>
          <%= f.input :price_per_hour, label: t("price")  %>
          <%= f.input :start_date, html5:true, label: t("startdate")  %>
          <%= f.input :end_date, html5:true, label: t("enddate")  %>
          <%= f.input :start_time, label: t("starttime")  %>
          <%= f.input :end_time, label: t("endtime")  %>
          <%= f.input :description, label: t("description")  %>
          <%= f.input :photo, as: :file, label: t("photo") %>
          <%= f.submit t("updateyourjob"), class: "btn btn-success" %>
        <% end %>
        <%= link_to t("back"), my_jobs_path, class: "btn btn-secondary mt-2" %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row mt-3 mb-4">
    <div class="col">
      <h3><%= t("AvailableJobs") %></h3>
          <div data-controller="search-jobs">
              <div class="row">
                <div class="col-6">
                  <div class = "search">
                    <%= form_with url: jobs_path, method: :get, html: {class:
                      "mb-4 input-lg", data: {search_jobs_target: "form"}} do |f| %>
                        <%= f.text_field :query,
                                          class: "form-control heightindex",
                                          placeholder:t("SearchForAJob"),
                                          value: params[:query],


                        data: {
                          search_jobs_target: "input",
                          action: "keyup->search-jobs#update"
                          } %>
                        <%= f.hidden_field :locale, value: params[:locale] %>
                  </div>
                </div>
                    <% end %>



          <div class="col-6 mt-4 rounded">
            <div class="accordion " id="accordionExample">
              <div class="accordion-item ">

                <h3 class="accordion-header" id="headingTwo">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    <%= t("advancedsearch") %>
                  </button>
                </h3>
                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <div class = "search">

                      <%= form_with url: jobs_path, method: :get, html: {class: "mb-4", data: {search_jobs_target: "form"}} do |f| %>
                      <%= f.hidden_field :locale, value: params[:locale] %>
                      <%= f.select :category, options_for_select([[t("category"),""],[t('painting'), 'painting'], [t('babysitting'), 'babysitting'], [t('deliveries'), 'deliveries'], [t('cleaning'), 'cleaning'], [t('petsitting'), 'petsitting'], [t('others'), 'others']], params[:category]), {}, class: "custom-width-he" %>
                      <%= f.text_field :city, class: "custom-width", placeholder: t("city"), value: params[:city] %>
                      <%= f.number_field :price, class: "custom-width", placeholder: t("price"), value: params[:price] %>
                      <%= f.date_field :date, class: "custom-width-hed", placeholder: t("date"), value: params[:date] %>

                      <div class="row">
                      <div class="col-3">
                        <%= f.submit t("search"), class: "btn btn-success mt-3" %>
                      </div>
                      <div class="col-9 mt-3">
                        <%=link_to t("cleanfilters"), jobs_path, class:"btn btn-secondary", style: "text-decoration:none; font-size: 15px;" %>
                      </div>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          </div>
            <%= link_to t("back"), root_path, class: "btn btn-success mt-3" %>



          <div>
            <%= render "list", jobs: @jobs %>
          </div>

          <%# <div style="width: 100%; height: 600px;" %>
            <%# data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>
            <%# data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>
          <%# </div> %>

      </div>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>
<div class="container">
  <div class = "form">
    <div class="row mt-3 mb-4">
      <div class="col">
        <h2> <%= t("newjob") %> </h2>
        <%= simple_form_for @job  do |f| %>

          <%= f.input :name, label: t("name")  %>
          <%= f.input :address, label: t("address")  %>
          <%= f.input :city, label: t("city")  %>
          <%= f.input :category, collection: [t('painting'), t('babysitting'), t('deliveries'), t('cleaning'), t('petsitting'), t('others')], include_blank: false, label: t('category') %>
          <%= f.input :qty_hour, label: t("qtyhour")  %>
          <%= f.input :price_per_hour, label: t("price")  %>
          <%= f.input :start_date, html5:true, label: t("startdate")  %>
          <%= f.input :end_date, html5:true, label: t("enddate")  %>
          <%= f.input :start_time, label: t("starttime")  %>
          <%= f.input :end_time, label: t("endtime")  %>
          <%= f.input :description, label: t("description")  %>
          <%= f.input :photo, as: :file, label: t("photo") %>
          <%= f.submit t("createjob"), class: "btn btn-success" %>

        <% end %>

        <%= link_to t("back"), my_jobs_path, class: "btn btn-secondary mt-2" %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="row mt-4 mb-4">
    <div class="col-lg-6 col-md-6 justify-content-center">
      <div class="card-jobs pb-2">
        <% if @job.photo.key != nil %>
          <%= cl_image_tag @job.photo.key, crop: :fill %>
        <% else %>
        <% end %>
        <div class="card-jobs-info p-3">
          <div class="title p-2">
            <h4><%= @job.name.titleize%></h4>
          </div>
          <div class="row description p-2">
            <div class="col-3">
              <p class="detail"><strong><%= t('category') %></strong>
              <p class="detail"><strong><%= t("description") %></strong>
            </div>

            <div class="col-9">
              <%if  @job.category == "Painting" %>
                <span class="grey"> <%= t("painting")  %></span></p>
              <% end %>
              <%if  @job.category == "Babysitting" %>
                <span class="grey"> <%= t("babysitting")  %></span></p>
              <% end %>
              <%if  @job.category == "Deliveries" %>
                <span class="grey"> <%= t("deliveries")  %></span></p>
              <% end %>
              <%if  @job.category == "Cleaning" %>
                <span class="grey"> <%= t("cleaning")  %></span></p>
              <% end %>
              <%if  @job.category == "Petsitting" %>
                <span class="grey"> <%= t("petsitting")  %></span></p>
              <% end %>
              <%if  @job.category == "Others" %>
                <span class="grey"> <%= t("other")  %></span></p>
              <% end %>
              
              <span class="grey"> <%= @job.description %></span></p>
            </div>

            <div class="col-3">
              <p class="detail"><strong><%= t("address") %></strong>
              <p class="detail"><strong><%= t("dates") %></strong>
              <p class="detail"><strong><%= t("time") %></strong>
              <p class="detail"><strong><%= t("qtyhour")  %></strong>
              <p class="detail"><strong><%= t("price")  %></strong>
            </div>

            <div class="col-9">
              <span class="grey"> <%= @job.address %>, <%= @job.city %> </span></p>
              <span class="grey"> <%= @job.start_date.strftime('%d/%m/%Y') %></span>&nbsp<%= t("to")%>&nbsp<span class="grey"><%= @job.end_date.strftime('%d/%m/%Y') %></span></p>
              <span class="grey"><%= @job.start_time.strftime("%k:%M") %></span>&nbsp<%= t("to")%>&nbsp<span class="grey"><%= @job.end_time.strftime("%k:%M") %></span></p>
              <span class="grey"> <%= @job.qty_hour %> hr</span></p>
              <span class="grey"> <%= @job.price_per_hour %> USD</span></p>
            </div>

          </div>
          <% if user_signed_in? %>
            <% if current_user.id == @job.user_id %>
            <% else %>
              <div class="row">
                <div class="col-3">
                  <%= button_to t("applyhere"), job_my_jobs_path(@job), class:"btn btn-success" %>
                </div>
                <div class="col-9">
                 <%= link_to t("sendmessage"), chatroom_path(1, employer_id: @job.user_id), class:"btn btn-secondary" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-3">
      <%= link_to t("back"), jobs_path, class:"btn btn-secondary mt-3" %>
      </div>
    </div>
    <div class="map2 col-6">
        <div style="width: 100%; height: 757px;"
          class="shadow"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>
  </div>
</div>