config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :jobs do
    resources :my_jobs, only: [:create ]
  end

  resources :my_jobs, only: [:index]

  resources :reviews, only: [:index, :new, :create]

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :users do
    resources :reviews, only: [ :new, :create ]
  end

  post "my_jobs/change_status", to: "my_jobs#change_status"

  post '/change_locale', to: 'application#change_locale'

  resources :meetings
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

    <div class="col-3">
      <div class="footer-discover">
        <a href="#"><strong><p style="padding-bottom: 10px; margin: 0px; font-size: 16px";><%= t("helpandinformation") %></p></strong></a>
        <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("help") %></p></a>
        <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("lookforwork") %></p></a>
        <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("servicesbycity") %></p></a>
        <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("accountsetup") %></p></a>
      </div>
    </div>

      <div class="col-3">
        <div class="footer-about">
          <a href="#"><strong><p style="padding-bottom: 10px; margin: 0px; font-size: 16px";><%= t("aboutjobby") %></p></strong></a>
          <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("aboutus") %></p></a>
          <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("careersatjobby") %></p></a>
          <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("contactus") %></p></a>
          <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("blog") %></p></a>
        </div>
      </div>

      <div class="col-3">
        <div class="footer-more">
          <a href="#"><strong><p style="padding-bottom: 10px; margin: 0px; font-size: 16px";><%= t("morefromjobby") %></p></strong></a>
          <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("mobileandjobbyapps") %></p></a>
          <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("jobbyinlatam") %></p></a>
          <a href="#"><p style="padding: 0px; margin: 0px; font-size: 14px";><%= t("jobbyineurope") %></p></a>
        </div>
      </div>

      <div class="col-3">
        <div class="footer-links">
          <strong><p style="padding-bottom: 10px; margin: 0px; font-size: 16px";><%= t("followus") %></p></strong>
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
     <%= image_tag "logo.png" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% end %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">


         <!--
          <li class="nav-item dropdown mt-2 globe">
            <%= image_tag "mundo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style: "width: 20px" %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= form_with(url: "/change_locale", method: "post", local: false, authenticity_token: true, remote: true) do |f| %>
                <%= f.select :locale, { "English" => "en", "Español" => "es" } %>
                <%= f.submit "Change language", button: false %>
              <% end %>
            </div>
          </li>
          -->
          <li>
            <%= link_to change_locale_path(locale: "es"), data: {turbo_method: :post} do %>
              <%= image_tag "espanol.png", :size=>"37x28", class: "me-3  mte" %>

            <% end %>
          </li>
          <li>
            <%= link_to change_locale_path(locale: "en"), data: {turbo_method: :post} do %>
              <%= image_tag "inglaterra1.png", :size=>"25x25", class: "me-3 mt-2" %>
            <% end %>

          </li>


        <% if user_signed_in? %>

          <li class="nav-item active">
            <%= link_to t("jobs"), jobs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t("messages"), chatroom_path(1), class: "nav-link" %>
          </li>


          <li class="nav-item dropdown">
          <% if current_user.photo.key != nil %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "profile.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.nickname.nil? %>
               <%= link_to current_user.email, edit_user_registration_path, class: "dropdown-item" %>
              <% else %>
                <%= link_to current_user.nickname.capitalize, edit_user_registration_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to t("myjobs"), my_jobs_path, class: "dropdown-item" %>
              <%= link_to t("calendar"), meetings_path, class: "dropdown-item"%>
              <%= link_to t("publishajobhere"), new_job_path, class: "dropdown-item"%>
              <%= link_to t("logout"), destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>

        <% else %>
          <li class="nav-item">
            <%= link_to t("login"), new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>