config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :jobs do
    resources :my_jobs, only: [:create ]
  end

  resources :my_jobs, only: [:index]

  resources :reviews, only: [:index, :new, :create]

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :users do
    resources :reviews, only: [ :new, :create ]
  end

  post "my_jobs/change_status", to: "my_jobs#change_status"

  post '/change_locale', to: 'application#change_locale'

  resources :meetings
end

app/models/my_job.rb
class MyJob < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :job_id, uniqueness: {scope: :user_id}
  enum status: [:apply, :pending, :accepted, :canceled, :rejected  ]

end

app/controllers/my_jobs_controller.rb
class MyJobsController < ApplicationController

  def index
    @my_jobs = MyJob.where(user_id: current_user)
    @my_published_jobs = Job.where(user: current_user)

  end

  def create

    @job = Job.find(params[:job_id])
    @my_job = MyJob.create(user:current_user, job:@job)
    redirect_to my_jobs_path, notice: t("thanksforapplying")
  end

  def change_status
    @job=MyJob.find(params[:format])
    if params[:status] == "aceptar"

      @job.status = 2
      if @job.save
         redirect_to my_jobs_path, notice: t("youhaveaccepted")
      end
    end

    if params[:status] == "pending"
      @job.status = 1
      if @job.destroy
        redirect_to my_jobs_path, notice: t("youhavecancelled")
     end
    end

    if params[:status] == "cancelar"
      @job.status = 4
      if @job.save
         redirect_to my_jobs_path, notice: t("youhavedeclined")
      end
    end
  end


end

app/views/my_jobs/index.html.erb
<div class="container mb-3">
  <div class = "mt-5 mb-5">
    <h3><%= t("myjobsstatus") %></h3>
  </div>
  <% if @my_jobs.size > 0 %>
    <div class= "mt-5 mb-3">
      <h4><%= t("myappliedjobs") %></h4>
    </div>
      <div class="row mt-3">
        <% @my_jobs.each do |my_job| %>
          <div class="col-lg-4 col-md-4 col d-flex justify-content-center">
            <div class="card-applied-jobs mb-5 justify-content-center">
              <% if my_job.job.photo.key != nil %>
                    <%= cl_image_tag my_job.job.photo.key, height: 300, width: 300, crop: :fill %>
                  <% else %>
              <% end %>
                <div class="card-infos">
                  <div class="title p-2">
                   <h5><%= my_job.job.name %></h5>
                  </div>
                  <p><%= t("startdate") %>: <%= my_job.job.start_date.strftime('%d/%m/%Y')  %></p>
                  <p><%= my_job.job.description  %></p>

                  <%if my_job.status == "pending" %>
                      <p><%= t("pending") %></p>
                  <%elsif my_job.status == "accepted" %>
                       <p><%= t("accepted") %></p>
                  <%elsif my_job.status == "rejected" %>
                       <p><%= t("rejected") %></p>
                  <% end %>
                  <%# <p><%= my_job.status.capitalize  %>
                  <p><%= button_to t("cancelyourrequest"), my_jobs_change_status_path(my_job, status: "pending"), class: "btn btn-warning" %></p>
                </div>
            </div>
          </div>
        <% end %>
  <% end %>
      </div>

<div class="container">

    <% if @my_published_jobs.size > 0 %>
      <div class= "mt-3 mb-3">
        <h4><%= t("mypublishedjobs") %></h4>
      </div>
      <% @my_published_jobs.each do |my_published_job| %>
        <div class="row card-my-jobs mb-3 p-3">
          <div class="mt-3 mb-4">
          <h6><strong><%= my_published_job.name %></strong></strong></h6>
          <%= t("startdate") %>: <%= my_published_job.start_date.strftime('%d/%m/%Y')  %>&nbsp&nbsp
          <%= link_to t("moredetails"), job_path(my_published_job), class: "btn btn-success m-1" %>
          <%= link_to t("edit"), edit_job_path(my_published_job), class: "btn btn-secondary m-1" %>
          <%= link_to t("cancel"), job_path(my_published_job), class: "btn btn-warning m-1", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
          </div>
          <div class="col-12">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col"><%= t("nickname") %></th>
                  <th scope="col"><%= t("rating") %></th>
                  <th scope="col"><%= t("status") %></th>
                  <th scope="col"><%= t("action") %>
                </tr>
              </thead>
              <tbody>
                <% my_published_job.my_jobs.each do |applicant| %>
                  <tr>
                    <td><%=applicant.user.nickname%></td>
                    <% rating = 5 - applicant.user.rating %>
                    <td><%= link_to"#{'★' * applicant.user.rating}#{'☆' * rating}",user_path(applicant.user.id), class: "star-rating" %></td>
                     <%if applicant.status == "pending" %>
                        <td><%= t("pending") %></td>
                      <%elsif applicant.status == "accepted" %>
                       <td><%= t("accepted") %></td>
                      <%elsif applicant.status == "rejected" %>
                       <td><%= t("rejected") %></td>
                      <% end %>

                    <% unless applicant.status == "accepted" ||  applicant.status == "rejected" %>
                    <td>
                      <div class="row">
                        <div class="col-3">
                          <%= button_to t("accept"), my_jobs_change_status_path(applicant, status: "aceptar"), class: "btn btn-success" %>
                        </div>
                        <div class="col-9">
                          <%= button_to t("decline"), my_jobs_change_status_path(applicant, status: "cancelar"),  class: "btn btn-warning" %>
                        </div>
                      </div>
                    </td>
                    <% else %>
                    <td>
                      <div class="row">
                        <div class="col-4">
                          <%= link_to t("sendmessage"), chatroom_path(1), class: "btn btn-secondary" %>
                        </div>
                        <div class="col-8">
                          <%= link_to t("leavereview"), user_path(applicant.user.id), class: "btn btn-success" %>
                        </div>
                      </div>
                    </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
    <% end %>
    <%= link_to t("calendar"), meetings_path, class: "btn btn-success mb-3"%>
  </div>
</div>